parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: sf_db
    database_user: root
    database_password: parola
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: fd0d51282c5dfc30d22f6b2f8350cf95b00ebdf5
    database_path: null
